### ISSUE TITLE
Rich text fields display html tags

### ISSUE THREAD

**Issue by anilsonmez-simsoft** [NCI-Agency/anet#3859] opened 2021-09-17 12:31 UTC
**Describe the bug**
Rich text field assessments display HTML tags on the sidebar notes and instant assessment results.

**Expected behavior**
Rich text values should be displayed with the correct styling.

**Comment by gjvoosten** [comment] 2021-09-20 06:45
Duplicate of #3065 (which is not a bug but an enhancement)

**Closed** 2021-09-28 09:11 UTC
Labels: bug, Sprint 10
