### ISSUE TITLE
Link to configuration in dev-setup broken

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3178] opened 2020-09-03 10:21 UTC
In [Set Up Gradle](https://github.com/NCI-Agency/anet/blob/candidate/docs/dev-setup.md#set-up-gradle), the link to "ANET Configuration documentation" is broken.

**Comment by gjvoosten** [comment] 2020-09-03 10:38
Duplicate of NCI-Agency/anet#3033

**Closed by gjvoosten** 2020-09-03 10:38 UTC
Labels: bug, duplicate
