### ISSUE TITLE
Assessment text is displaying &#39; instead of an apostrophe

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3247] opened 2020-10-14 13:50 UTC
**Describe the bug**
The text for assessments (tasks.text) is displaying &#39; instead of an apostrophe (single quote).

**To Reproduce**
1. Go to an effort / assessment
2. Select the Notes icon at the top right of the page. Result: assessments will be displayed
3. See error in the text of the assessment

**Expected behavior**
An apostrophe (single quote) should be displayed instead of &#39

**Screenshots**
None

**Environment (please complete the following information):**
Firefox 78.2.0esr

**Additional context**
N/A

**Comment by gjvoosten** [comment] 2020-10-14 14:04
Duplicate of NCI-Agency/anet#3065

**Closed by gjvoosten** 2020-10-14 14:04 UTC
Labels: bug, duplicate
