### ISSUE TITLE
Standardize display of person name and rank

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#529] opened 2018-03-08 10:25 UTC
The used format should be:
rank name

**Comment by dspCarlson** [comment] 2018-05-10 04:57
@VassilIordanov 
Items 6 and 7 might be duplicates of 1 and 2 above.....
More places where rank is not displayed

5. Using "Advanced search," select the "Positions" button.  The Advanced Search results for "Positions" returns the "Current Occupant" but the current occupant does not have the rank displayed

6. Using "Advanced search," select the "Reports" button.  The Advanced Search results for "Reports" returns a list of reports that include primary advisor attendee and primary principal attendee.  Both attendees do not have their rank displayed.  I believe this is a duplicate of 1 and 2 above.  I assume the same query returns the results for reports no matter when the results are displayed.

7. On the Daily Rollup, reports are listed at the bottom.  The primary advisor attendee and primary Afghan attendee do not have their rank displayed.  I believe this is a duplicate of 1, 2 and 6 above.

**Closed** 2018-05-10 12:56 UTC
Labels: enhancement
