### ISSUE TITLE
Set Domain User Name to Null

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#125] opened 2017-08-10 10:31 UTC
@gjvoosten #65 does not set the domain user name to NULL during testing

**Comment by dspCarlson** [comment] 2017-08-14 13:14
@VassilIordanov  #91 
Tried six new test cases without success

**Comment by VassilIordanov** [comment] 2017-08-14 14:08
duplicate of NCI-Agency/anet#65

**Closed** 2017-08-14 15:17 UTC
