### ISSUE TITLE
My tasks shows all active tasks when user has no position

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#3226] opened 2020-10-01 12:25 UTC
When the logged in user is not assigned to a position, the My Objective / Efforts page will display all active tasks for both lists of tasks: tasks the user is responsible for and tasks tasked for his/her organization (as he/she has no organization).

**To Reproduce**
1. Create a new user and a profile for the new user
2. Click in the left navigation menu on "My Objective / Efforts"
3. The page will contain 2 tables with all active tasks

**Expected behavior**
When the user is not assigned a position, he/she should not be able to see the My Objective / Efforts and My Counterparts pages, as they retrieve data related to the user's position.

**Comment by cemalettin-simsoft** [comment] 2020-10-06 07:55
I can( was trying to) fix this in the #3212 since i already change a lot in the My Tasks & My Counterparts page

**Comment by cemalettin-simsoft** [comment] 2020-10-06 08:02
I saw two possible solutions when user has no position yet: 

1. Remove the page (routing & nav links)
2. Don't remove the page but show a warning at the page / or empty page (This has the advantage that people can get used to the UI, getting assigned to a position wouldn't be a big change in the UI)

**Comment by cemalettin-simsoft** [comment] 2020-10-09 06:47
> I saw two possible solutions when user has no position yet:
> 
> 1. Remove the page (routing & nav links)
> 2. Don't remove the page but show a warning at the page / or empty page (This has the advantage that people can get used to the UI, getting assigned to a position wouldn't be a big change in the UI)

According to how the previous code was written, solution 1 was intended, but there was a logic bug so it wasn't working. So, i went with the solution 1 as well, since it was the intended solution from the beginning

**Closed** 2020-10-19 13:43 UTC
Labels: bug
