### ISSUE TITLE
The text for assessments (tasks.text) is displaying &amp; instead of an ampersand

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3248] opened 2020-10-14 13:53 UTC
**Describe the bug**
The text for assessments (tasks.text) is displaying &amp; instead of an ampersand.

**To Reproduce**
1. Go to an effort / assessment
2. Select the Notes icon at the top right of the page. Result: assessments will be displayed
3. See error in the text of the assessment

**Expected behavior**
An ampersand should be displayed instead of &amp;

**Screenshots**
None

**Environment (please complete the following information):**
Firefox 78.2.0esr

**Additional context**
N/A

**Comment by gjvoosten** [comment] 2020-10-14 14:04
Duplicate of NCI-Agency/anet#3065

**Closed by gjvoosten** 2020-10-14 14:04 UTC
Labels: bug, duplicate
