### ISSUE TITLE
Error message displayed when a new user tries to create his/her profile

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3491] opened 2021-03-15 12:26 UTC
**Describe the bug**

A new user was creating their ANET profile today.  After filling in all the data fields, an error message was displayed when the user selected the "Save" button

The error message displayed was: Forbidden: Exception while fetching data (/updatePerson): You do not have permissions to edit this person. 

**To Reproduce**

Condition 1: A new user has assumed his/her predecessor's ANET position and profile, because the Active Directory account is role-based, i.e. the domain user name is used more than once by successive users.

1. A new user accesses ANET.  Result: the new predecessor's name is displayed in the banner
2. The new user selects the "(edit)" link to the right of the predecessor's name.  Result: the predecessor's profile is displayed
3. The new user selects the blue "Edit" button in the top-right of the profile page.  Result: the profile page is now in edit mode
4. The new user selects the white "This is not <predecessor's name>" button.  Result: a pop-up window is displayed with four choices.
5. The new user selects the "<predecessor's name> has left and has a replacement" option button.  Note: the wording on the option button is slightly different for users than for me, an administrator.
6. The new user selects the blue "Save" button in the bottom-right of the pop-up window.  Result: the onboarding page is displayed
7. The new user selects the blue "Create Profile" in the center of the onboarding page.  Result: a blank profile page is displayed
8. The new user completes all required fields, i.e. surname, given name, email address, phone number, rank, gender, nationality, and end of tour date.
9. The new user selects the blue "Save Person" button at the top-right of the profile page.  Result: the profile is not saved.  An error message is displayed, i.e. "Forbidden: Exception while fetching data (/updatePerson): You do not have permissions to edit this person."

**Expected behavior**
When clicking the blue "Save Person" button, the new user's profile should be saved.

**Screenshots**
Not available

**Environment (please complete the following information):**
 - Microsoft Edge

**Additional context**
I watched as the new user tried to create his profile.

**Comment by gjvoosten** [comment] 2021-03-15 15:08
This is caused by a race condition, causing sometimes multiple simultaneous requests to go through the authentication filter, which in this case may end up creating multiple new accounts. The onboarding then picks the 'wrong' one, which the user is not allowed to update.

This should be fixed by some form of synchronization, ensuring that at most _one_ new account gets created in such cases. However, we don't want to completely serialize _all_ calls to the authentication filter, as that would slow things down too much for users that already exist in the database.

**Closed** 2021-03-16 10:01 UTC
Labels: bug
