### ISSUE TITLE
Remove "Tasks" Section from an Advisor Organization's Page

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#450] opened 2018-02-08 12:02 UTC
All tasks are now owned by the business owner.  Tasks are no longer assigned to individual advisor organizations.

Remove the "Tasks" section from an advisor organization, except the business owner's advisor page.

Remove the "Tasks" link in the left-hand column of an advisor organization's page, except for the business owner's advisor page.

**Comment by VassilIordanov** [comment] 2018-02-08 12:10
Tasks should remain definable per organization in ANET. 
It may be worth considering which organizations are allowed to maintain tasks.

**Comment by dspCarlson** [comment] 2018-02-14 07:16
When instructing super users, they want to know why the "Tasks" section is empty or what the "Tasks" section is for.

Only one organization is allowed to maintain tasks and that is the business owner.  The super users from the advisor organizations were messing up the task/PoAM data so bad, the business owner requested they be the only personnel allowed to create/edit the tasks.

Maybe only ANET administrators should be able to create/edit tasks.  I do not belong to the business owner advisor organization and cannot create/edit tasks.

When a super user clicks the "Edit" button for their organization, the advisor organization's obsolete PoAMs are still displayed in the "Tasks" section.  But there is no sense in displaying the obsolete PoAMs.  Obsolete PoAMs can still be found with Advanced search.

**Comment by VassilIordanov** [comment] 2018-02-15 13:11
duplicate of  #236

**Closed by VassilIordanov** 2018-02-15 13:11 UTC
Labels: duplicate, enhancement
