### ISSUE TITLE
Save a location using an MGRS grid coordinate

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1161] opened 2018-12-07 00:51 UTC
Users would like to enter grid coordinates without choosing a location on the ANET map(s).

Note: The military uses MGRS grid coordinates, not longitude/latitude.

**Comment by VassilIordanov** [comment] 2018-12-17 12:05
duplicate of #244

**Closed by VassilIordanov** 2018-12-17 12:05 UTC
