### ISSUE TITLE
When adding principal attendees, all counterparts are displayed in one list instead of by page

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1949] opened 2019-07-06 13:18 UTC
To recreate:

1. Assigned myself 15 principals
2. Made myself a report author instead of an administrator
3. Created a new report
4. Clicked on the "Attendees" data field to display the widget
5. Selected "My counterparts"

Result: All 15 principal counterparts are displayed in one long list.  The pagination numbers (in this case three page numbers) are also displayed at the bottom of the widget.  Clicking on the three different page numbers does not change the principals in the list.

**Comment by maradragan** [comment] 2019-07-08 11:25
The counterparts is not using a regular search and this is why the pagination doesn't work. Making the counterparts a regular search should be part of the GraphQL improvements.

**Comment by maradragan** [comment] 2019-09-10 11:14
Duplicate of #1954

**Closed by maradragan** 2019-09-10 11:14 UTC
Labels: bug
