### ISSUE TITLE
Uuids are being displayed in the filtered search

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3267] opened 2020-10-27 07:14 UTC
**Describe the bug**
For the "Reports" filtered search, Uuids are being displayed for the following three filters: "Author," "Attendee" and "Pending Approval Of."

**To Reproduce**
1. At the top-left of any ANET page, select the blue "Everything filtered Status: Active" link.  Result: the filtered search pop-up window is displayed

2. Select the "Reports" button in the pop-up window.  Result: the blue "+Add another filter" link is displayed in the lower left of the pop up window

3. Select the blue "+Add another filter" link.  Result: a drop-down list of possible report filters is displayed

4. Select the "Author," "Attendee" or "Pending Approval Of" filter.  Result: a data field to enter data is displayed

5. Click the mouse inside the data field.  Result: A list of Uuids is displayed in a drop-down list.

6. See error: Uuids are displayed in the drop-down list instead of names

**Expected behavior**
When clicking the mouse inside the data field, a list of names should be displayed.

**Screenshots**
N/A

**Environment (please complete the following information):**
Firefox

**Additional context**
This bug also occurred when selecting attendees for an engagement report.  Vassil was able to quickly fix the bug.

There are probably more of this type of bug in ANET.  I just need to do a thorough investigation / test.

**Comment by cemalettin-simsoft** [comment] 2020-10-27 07:16
This is probably related to https://github.com/NCI-Agency/anet/issues/3245

**Comment by gjvoosten** [comment] 2020-10-27 07:38
> This is probably related to #3245

And most likely NCI-Agency/anet#3125 which should be updated.

**Comment by gjvoosten** [comment] 2020-10-29 08:07
NCI-Agency/anet#3125 has been merged.

**Comment by VassilIordanov** [comment] 2020-12-16 13:47
Issue is still present according to @dspCarlson

**Comment by cemalettin-simsoft** [comment] 2020-12-16 13:59
Has it been always present or has it just started to happen again after the most recent release?

**Comment by cemalettin-simsoft** [comment] 2020-12-16 14:12
I cannot reproduce this on `candidate` or the latest tag `2.1.37`. Maybe it is somewhere else now?

**Comment by dspCarlson** [comment] 2020-12-16 15:19
@cemalettin-simsoft It was never fixed

**Comment by gjvoosten** [comment] 2020-12-16 15:43
I can reproduce this; the people with uuid's you see are accounts that have signed up but haven't completed onboarding. Their `name` field in the `people` table is empty and they have `pendingVerification` set to `1` (i.e. true). It appears `pendingVerification: false` is *not* being sent along in the query variables…

**Comment by VassilIordanov** [comment] 2020-12-23 17:44
still ongoing

**Comment by gjvoosten** [comment] 2020-12-24 09:01
> still ongoing

Was caused by a client running a previous version of ANET in their browser.
[Note: NCI-Agency/anet#3020 should be picked up to address that.]

**Closed by gjvoosten** 2020-12-24 09:01 UTC
Labels: bug
