### ISSUE TITLE
Implied "Approval Process" for prinicipal Organizations 

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#29] opened 2017-07-11 10:15 UTC
"When reviewing an organization, the ""Approval steps"" section displays a message:
 
""This organization doesn't have any approval steps""
 
This message implies the principal organization doesn't have approval steps, but it could have approval steps.
 
Change the message to:
 
""This is a principal organization.  It will not have approval steps.""
 
Or better yet, don't display ""Approval steps"" when it is a principal organization."

Reference item 22

**Comment by dspCarlson** [comment] 2018-09-18 04:07
This is a duplicate of #548.  I am closing this issue because #548 is concise and the solution needed.

**Closed by dspCarlson** 2018-09-18 04:07 UTC
Labels: enhancement
