### ISSUE TITLE
History of Report Approval Not Available After Report is Released

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#98] opened 2017-07-31 08:35 UTC
During the pending approval process, the approval process history must be displayed.  The approval process history includes all previous steps.  For each step the following information is displayed:
1. Step number
2. Step name
3. Approver's name who approved the step
4. Date/Time the the approver approved the step

After a report is released, the entire report history must be available to include the four data items above for every approval step.

Reference item 57

**Comment by dspCarlson** [comment] 2017-08-02 08:01
Issue 20 can be merged with this issue.

**Comment by VassilIordanov** [comment] 2017-08-02 10:48
duplicate of #20

**Comment by dspCarlson** [comment] 2017-08-02 14:16
Even though this issue is closed, this issue describes the requirement better than issue 20.

**Comment by VassilIordanov** [comment] 2017-08-02 15:55
@dspCarlson - not anymore ;)

**Comment by dspCarlson** [comment] 2017-11-18 13:24
Test Failed: Met with the customer today about this issue.  They still need to know the report approval history after the report has been released (as per the original description).

**Comment by VassilIordanov** [comment] 2017-11-28 13:34
I believe, pending reports display approval history when viewed. I suggest enable the same for released reports. Will that meet the request?

**Comment by VassilIordanov** [comment] 2017-11-28 14:49
fixed and documented in #20

**Closed by VassilIordanov** 2017-11-28 14:49 UTC
